/********************************************************
*                                                       *
*   Copyright (C) Microsoft. All rights reserved.       *
*                                                       *
********************************************************/

// This file auto generated by the TFS Build Number Targets.
using System.Reflection; 

[assembly: AssemblyVersion("2.6.41114.1")]
[assembly: AssemblyFileVersion("2.6.41114.1")]
