// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using MicrosoftResearch.Infer;
using MicrosoftResearch.Infer.Distributions;
using MicrosoftResearch.Infer.Collections;
using MicrosoftResearch.Infer.Factors;

namespace MicrosoftResearch.Infer.Models.User
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 2.6.41114.1 at 11:57 PM on Friday, November 14, 2014.
	/// </remarks>
	public partial class GaussianSparseBinaryBpmTraining_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Field backing the InstanceCount property</summary>
		private int instanceCount;
		/// <summary>Field backing the FeatureCount property</summary>
		private int featureCount;
		/// <summary>Field backing the InstanceFeatureCounts property</summary>
		private int[] instanceFeatureCounts;
		/// <summary>Field backing the FeatureValues property</summary>
		private double[][] featureValues;
		/// <summary>Field backing the FeatureIndexes property</summary>
		private int[][] featureIndexes;
		/// <summary>Field backing the WeightPriors property</summary>
		private DistributionStructArray<Gaussian,double> weightPriors;
		/// <summary>Field backing the WeightConstraints property</summary>
		private DistributionStructArray<Gaussian,double> weightConstraints;
		/// <summary>Field backing the Labels property</summary>
		private bool[] labels;
		/// <summary>The number of iterations last computed by Constant. Set this to zero to force re-execution of Constant</summary>
		public int Constant_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1. Set this to zero to force re-execution of Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1</summary>
		public int Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_iterationsDone;
		/// <summary>True if Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1 has performed initialisation. Set this to false to force re-execution of Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1</summary>
		public bool Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised;
		/// <summary>The number of iterations last computed by Changed_WeightPriors. Set this to zero to force re-execution of Changed_WeightPriors</summary>
		public int Changed_WeightPriors_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3. Set this to zero to force re-execution of Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3</summary>
		public int Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_iterationsDone;
		/// <summary>True if Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3 has performed initialisation. Set this to false to force re-execution of Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3</summary>
		public bool Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised;
		/// <summary>The number of iterations last computed by Changed_InstanceCount. Set this to zero to force re-execution of Changed_InstanceCount</summary>
		public int Changed_InstanceCount_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_InstanceCount_InstanceFeatureCounts. Set this to zero to force re-execution of Changed_InstanceCount_InstanceFeatureCounts</summary>
		public int Changed_InstanceCount_InstanceFeatureCounts_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6. Set this to zero to force re-execution of Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6</summary>
		public int Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_iterationsDone;
		/// <summary>True if Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6 has performed initialisation. Set this to false to force re-execution of Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6</summary>
		public bool Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised;
		/// <summary>The number of iterations last computed by Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7. Set this to zero to force re-execution of Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7</summary>
		public int Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone;
		/// <summary>Messages to use of 'Weights'</summary>
		public DistributionStructArray<Gaussian,double>[] Weights_uses_F;
		/// <summary>Messages from use of 'Weights'</summary>
		public DistributionStructArray<Gaussian,double>[] Weights_uses_B;
		/// <summary>Buffer for ReplicateOp_Divide.UsesAverageConditional<DistributionStructArray<Gaussian, double>></summary>
		public DistributionStructArray<Gaussian,double> Weights_uses_F_marginal;
		/// <summary>Buffer for JaggedSubarrayOp<double>.ItemsAverageConditional<DistributionStructArray<Gaussian, double>, Gaussian, DistributionStructArray<Gaussian, double>></summary>
		public DistributionStructArray<Gaussian,double> Weights_uses_F_1__marginal;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Weights_FeatureIndexes_F;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal<DistributionStructArray<Gaussian, double>></summary>
		public DistributionStructArray<Gaussian,double> Weights_uses_B_toDef;
		/// <summary>Message to marginal of 'Weights'</summary>
		public DistributionStructArray<Gaussian,double> Weights_marginal_F;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> FeatureScores_F;
		public DistributionStructArray<Gaussian,double> Score_F;
		public DistributionStructArray<Gaussian,double> NoisyScore_F;
		/// <summary>Message from use of 'NoisyScore'</summary>
		public DistributionStructArray<Gaussian,double> NoisyScore_use_B;
		public DistributionStructArray<Gaussian,double> Score_B;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> FeatureScores_B;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> IndexedWeights_B;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'InstanceCount'</summary>
		public int InstanceCount
		{
			get {
				return this.instanceCount;
			}
			set {
				if (this.instanceCount!=value) {
					this.instanceCount = value;
					this.numberOfIterationsDone = 0;
					this.Changed_InstanceCount_iterationsDone = 0;
					this.Changed_InstanceCount_InstanceFeatureCounts_iterationsDone = 0;
					this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_iterationsDone = 0;
					this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised = false;
					this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised = false;
					this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
				}
			}
		}

		/// <summary>The externally-specified value of 'FeatureCount'</summary>
		public int FeatureCount
		{
			get {
				return this.featureCount;
			}
			set {
				if (this.featureCount!=value) {
					this.featureCount = value;
					this.numberOfIterationsDone = 0;
				}
			}
		}

		/// <summary>The externally-specified value of 'InstanceFeatureCounts'</summary>
		public int[] InstanceFeatureCounts
		{
			get {
				return this.instanceFeatureCounts;
			}
			set {
				if ((value!=null)&&(value.Length!=this.instanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.instanceCount)+" was expected for variable \'InstanceFeatureCounts\'");
				}
				this.instanceFeatureCounts = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_InstanceFeatureCounts_iterationsDone = 0;
				this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_iterationsDone = 0;
				this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised = false;
				this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'FeatureValues'</summary>
		public double[][] FeatureValues
		{
			get {
				return this.featureValues;
			}
			set {
				if ((value!=null)&&(value.Length!=this.instanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.instanceCount)+" was expected for variable \'FeatureValues\'");
				}
				this.featureValues = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised = false;
				this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised = false;
				this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'FeatureIndexes'</summary>
		public int[][] FeatureIndexes
		{
			get {
				return this.featureIndexes;
			}
			set {
				if ((value!=null)&&(value.Length!=this.instanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.instanceCount)+" was expected for variable \'FeatureIndexes\'");
				}
				this.featureIndexes = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised = false;
				this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised = false;
				this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'WeightPriors'</summary>
		public DistributionStructArray<Gaussian,double> WeightPriors
		{
			get {
				return this.weightPriors;
			}
			set {
				this.weightPriors = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised = false;
				this.Changed_WeightPriors_iterationsDone = 0;
				this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_iterationsDone = 0;
				this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_iterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'WeightConstraints'</summary>
		public DistributionStructArray<Gaussian,double> WeightConstraints
		{
			get {
				return this.weightConstraints;
			}
			set {
				this.weightConstraints = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised = false;
				this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised = false;
				this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_iterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'Labels'</summary>
		public bool[] Labels
		{
			get {
				return this.labels;
			}
			set {
				if ((value!=null)&&(value.Length!=this.instanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.instanceCount)+" was expected for variable \'Labels\'");
				}
				this.labels = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised = false;
				this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised = false;
				this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
			}
		}

		#endregion

		#region Methods
		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="InstanceCount") {
				return this.InstanceCount;
			}
			if (variableName=="FeatureCount") {
				return this.FeatureCount;
			}
			if (variableName=="InstanceFeatureCounts") {
				return this.InstanceFeatureCounts;
			}
			if (variableName=="FeatureValues") {
				return this.FeatureValues;
			}
			if (variableName=="FeatureIndexes") {
				return this.FeatureIndexes;
			}
			if (variableName=="WeightPriors") {
				return this.WeightPriors;
			}
			if (variableName=="WeightConstraints") {
				return this.WeightConstraints;
			}
			if (variableName=="Labels") {
				return this.Labels;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="InstanceCount") {
				this.InstanceCount = (int)value;
				return ;
			}
			if (variableName=="FeatureCount") {
				this.FeatureCount = (int)value;
				return ;
			}
			if (variableName=="InstanceFeatureCounts") {
				this.InstanceFeatureCounts = (int[])value;
				return ;
			}
			if (variableName=="FeatureValues") {
				this.FeatureValues = (double[][])value;
				return ;
			}
			if (variableName=="FeatureIndexes") {
				this.FeatureIndexes = (int[][])value;
				return ;
			}
			if (variableName=="WeightPriors") {
				this.WeightPriors = (DistributionStructArray<Gaussian,double>)value;
				return ;
			}
			if (variableName=="WeightConstraints") {
				this.WeightConstraints = (DistributionStructArray<Gaussian,double>)value;
				return ;
			}
			if (variableName=="Labels") {
				this.Labels = (bool[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="Weights") {
				return this.WeightsMarginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			if ((variableName=="Weights")&&(query=="MarginalDividedByPrior")) {
				return this.WeightsMarginalDividedByPrior();
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations<this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone) {
				this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised = false;
				this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised = false;
				this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
			}
			this.Constant();
			this.Changed_InstanceCount();
			this.Changed_InstanceCount_InstanceFeatureCounts();
			this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6(initialise);
			this.Changed_WeightPriors();
			this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1(initialise);
			this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3(initialise);
			this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(this.numberOfIterationsDone+additionalIterations, false);
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_iterationsDone==1) {
				return ;
			}
			// Create array for 'Weights_uses' Forwards messages.
			this.Weights_uses_F = new DistributionStructArray<Gaussian,double>[2];
			// Create array for 'Weights_uses' Backwards messages.
			this.Weights_uses_B = new DistributionStructArray<Gaussian,double>[2];
			this.Constant_iterationsDone = 1;
			this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_iterationsDone = 0;
			this.Changed_WeightPriors_iterationsDone = 0;
			this.Changed_InstanceCount_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount</summary>
		private void Changed_InstanceCount()
		{
			if (this.Changed_InstanceCount_iterationsDone==1) {
				return ;
			}
			// Create array for 'Weights_FeatureIndexes' Forwards messages.
			this.Weights_FeatureIndexes_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'FeatureScores_F'
			this.FeatureScores_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'Score_F'
			this.Score_F = new DistributionStructArray<Gaussian,double>(this.instanceCount);
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				this.Score_F[InstanceRange] = Gaussian.Uniform();
			}
			// Create array for replicates of 'NoisyScore_F'
			this.NoisyScore_F = new DistributionStructArray<Gaussian,double>(this.instanceCount);
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				this.NoisyScore_F[InstanceRange] = Gaussian.Uniform();
			}
			// Create array for replicates of 'NoisyScore_use_B'
			this.NoisyScore_use_B = new DistributionStructArray<Gaussian,double>(this.instanceCount);
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				this.NoisyScore_use_B[InstanceRange] = Gaussian.Uniform();
			}
			// Create array for replicates of 'Score_B'
			this.Score_B = new DistributionStructArray<Gaussian,double>(this.instanceCount);
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				this.Score_B[InstanceRange] = Gaussian.Uniform();
			}
			// Create array for replicates of 'FeatureScores_B'
			this.FeatureScores_B = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'IndexedWeights_B'
			this.IndexedWeights_B = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			this.Changed_InstanceCount_iterationsDone = 1;
			this.Changed_InstanceCount_InstanceFeatureCounts_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount and InstanceFeatureCounts</summary>
		private void Changed_InstanceCount_InstanceFeatureCounts()
		{
			if (this.Changed_InstanceCount_InstanceFeatureCounts_iterationsDone==1) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				// Create array for 'Weights_FeatureIndexes' Forwards messages.
				this.Weights_FeatureIndexes_F[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.instanceFeatureCounts[InstanceRange]);
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.instanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.Weights_FeatureIndexes_F[InstanceRange][InstanceFeatureRanges] = Gaussian.Uniform();
				}
				// Create array for 'FeatureScores' Forwards messages.
				this.FeatureScores_F[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.instanceFeatureCounts[InstanceRange]);
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.instanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.FeatureScores_F[InstanceRange][InstanceFeatureRanges] = Gaussian.Uniform();
				}
				// Create array for 'FeatureScores' Backwards messages.
				this.FeatureScores_B[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.instanceFeatureCounts[InstanceRange]);
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.instanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.FeatureScores_B[InstanceRange][InstanceFeatureRanges] = Gaussian.Uniform();
				}
				// Create array for 'IndexedWeights' Backwards messages.
				this.IndexedWeights_B[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.instanceFeatureCounts[InstanceRange]);
			}
			this.Changed_InstanceCount_InstanceFeatureCounts_iterationsDone = 1;
			this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount and InstanceFeatureCounts and must reset on changes to numberOfIterationsDecreased and WeightPriors and FeatureIndexes and FeatureValues and Labels and WeightConstraints</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6(bool initialise)
		{
			if ((this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_iterationsDone==1)&&((!initialise)||this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised)) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.instanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
					this.IndexedWeights_B[InstanceRange][InstanceFeatureRanges] = Gaussian.Uniform();
				}
			}
			this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_iterationsDone = 1;
			this.Changed_InstanceCount_InstanceFeatureCounts_Init_numberOfIterationsDecreased_WeightPriors_FeatureInd6_isInitialised = true;
			this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of WeightPriors</summary>
		private void Changed_WeightPriors()
		{
			if (this.Changed_WeightPriors_iterationsDone==1) {
				return ;
			}
			for(int _ind = 0; _ind<2; _ind++) {
				this.Weights_uses_F[_ind] = ArrayHelper.MakeUniform<DistributionStructArray<Gaussian,double>>(this.weightPriors);
			}
			// Message to 'Weights_uses' from Replicate factor
			this.Weights_uses_F_marginal = ReplicateOp_Divide.MarginalInit<DistributionStructArray<Gaussian,double>>(this.weightPriors);
			// Message to 'Weights_uses' from Replicate factor
			this.Weights_uses_B_toDef = ReplicateOp_Divide.ToDefInit<DistributionStructArray<Gaussian,double>>(this.weightPriors);
			// Create array for 'Weights_marginal' Forwards messages.
			this.Weights_marginal_F = ArrayHelper.MakeUniform<DistributionStructArray<Gaussian,double>>(this.weightPriors);
			this.Changed_WeightPriors_iterationsDone = 1;
			this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of WeightPriors and must reset on changes to numberOfIterationsDecreased and FeatureIndexes and InstanceCount and InstanceFeatureCounts and FeatureValues and Labels and WeightConstraints</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1(bool initialise)
		{
			if ((this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_iterationsDone==1)&&((!initialise)||this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised)) {
				return ;
			}
			for(int _ind = 0; _ind<2; _ind++) {
				this.Weights_uses_B[_ind] = ArrayHelper.MakeUniform<DistributionStructArray<Gaussian,double>>(this.weightPriors);
			}
			// Message to 'Weights_FeatureIndexes' from JaggedSubarray factor
			this.Weights_uses_F_1__marginal = JaggedSubarrayOp<double>.MarginalInit<DistributionStructArray<Gaussian,double>>(this.Weights_uses_F[1]);
			this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_iterationsDone = 1;
			this.Changed_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount_InstanceFeatureCo1_isInitialised = true;
			this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of WeightConstraints and WeightPriors and must reset on changes to numberOfIterationsDecreased and FeatureIndexes and InstanceCount and InstanceFeatureCounts and FeatureValues and Labels</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3(bool initialise)
		{
			if ((this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_iterationsDone==1)&&((!initialise)||this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised)) {
				return ;
			}
			// Message to 'Weights_uses' from EqualRandom factor
			this.Weights_uses_B[0] = ArrayHelper.SetTo<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B[0], this.weightConstraints);
			this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_iterationsDone = 1;
			this.Changed_WeightConstraints_WeightPriors_Init_numberOfIterationsDecreased_FeatureIndexes_InstanceCount3_isInitialised = true;
			this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and WeightPriors and FeatureIndexes and InstanceCount and InstanceFeatureCounts and FeatureValues and Labels and WeightConstraints</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7(int numberOfIterations)
		{
			if (this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone==numberOfIterations) {
				return ;
			}
			for(int iteration = this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone; iteration<numberOfIterations; iteration++) {
				// Message to 'Weights_uses' from Replicate factor
				this.Weights_uses_B_toDef = ReplicateOp_Divide.ToDef<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B, this.Weights_uses_B_toDef);
				// Message to 'Weights_uses' from Replicate factor
				this.Weights_uses_F_marginal = ReplicateOp_Divide.Marginal<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B_toDef, this.weightPriors, this.Weights_uses_F_marginal);
				// Message to 'Weights_uses' from Replicate factor
				this.Weights_uses_F[1] = ReplicateOp_Divide.UsesAverageConditional<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B[1], this.Weights_uses_F_marginal, 1, this.Weights_uses_F[1]);
				// Message to 'Weights_FeatureIndexes' from JaggedSubarray factor
				this.Weights_uses_F_1__marginal = JaggedSubarrayOp<double>.Marginal<DistributionStructArray<Gaussian,double>,Gaussian,object,DistributionStructArray<Gaussian,double>>(this.Weights_uses_F[1], this.IndexedWeights_B, this.featureIndexes, this.Weights_uses_F_1__marginal);
				for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
					// Message to 'Weights_FeatureIndexes' from JaggedSubarray factor
					this.Weights_FeatureIndexes_F[InstanceRange] = JaggedSubarrayOp<double>.ItemsAverageConditional<DistributionStructArray<Gaussian,double>,Gaussian,DistributionStructArray<Gaussian,double>>(this.IndexedWeights_B[InstanceRange], this.Weights_uses_F[1], this.Weights_uses_F_1__marginal, this.featureIndexes, InstanceRange, this.Weights_FeatureIndexes_F[InstanceRange]);
					for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.instanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
						// Message to 'FeatureScores' from Product factor
						this.FeatureScores_F[InstanceRange][InstanceFeatureRanges] = GaussianProductOp.ProductAverageConditional(this.featureValues[InstanceRange][InstanceFeatureRanges], this.Weights_FeatureIndexes_F[InstanceRange][InstanceFeatureRanges]);
					}
					// Message to 'Score' from Sum factor
					this.Score_F[InstanceRange] = FastSumOp.SumAverageConditional(this.FeatureScores_F[InstanceRange]);
					// Message to 'NoisyScore' from GaussianFromMeanAndVariance factor
					this.NoisyScore_F[InstanceRange] = GaussianFromMeanAndVarianceOp.SampleAverageConditional(this.Score_F[InstanceRange], 1.0);
					// Message to 'NoisyScore_use' from IsPositive factor
					this.NoisyScore_use_B[InstanceRange] = IsPositiveOp_Proper.XAverageConditional(Bernoulli.PointMass(this.labels[InstanceRange]), this.NoisyScore_F[InstanceRange]);
					// Message to 'Score' from GaussianFromMeanAndVariance factor
					this.Score_B[InstanceRange] = GaussianFromMeanAndVarianceOp.MeanAverageConditional(this.NoisyScore_use_B[InstanceRange], 1.0);
					// Message to 'FeatureScores' from Sum factor
					this.FeatureScores_B[InstanceRange] = FastSumOp.ArrayAverageConditional<DistributionStructArray<Gaussian,double>>(this.Score_B[InstanceRange], this.Score_F[InstanceRange], this.FeatureScores_F[InstanceRange], this.FeatureScores_B[InstanceRange]);
					for(int InstanceFeatureRanges = 0; InstanceFeatureRanges<this.instanceFeatureCounts[InstanceRange]; InstanceFeatureRanges++) {
						// Message to 'IndexedWeights' from Product factor
						this.IndexedWeights_B[InstanceRange][InstanceFeatureRanges] = GaussianProductOp.BAverageConditional(this.FeatureScores_B[InstanceRange][InstanceFeatureRanges], this.featureValues[InstanceRange][InstanceFeatureRanges]);
					}
					this.Weights_uses_F_1__marginal = JaggedSubarrayOp<double>.MarginalIncrement<DistributionStructArray<Gaussian,double>,Gaussian,DistributionStructArray<Gaussian,double>>(this.Weights_uses_F_1__marginal, this.Weights_FeatureIndexes_F[InstanceRange], this.IndexedWeights_B[InstanceRange], this.featureIndexes, InstanceRange);
				}
				// Message to 'Weights_uses' from JaggedSubarray factor
				this.Weights_uses_B[1] = JaggedSubarrayOp<double>.ArrayAverageConditional<Gaussian,DistributionStructArray<Gaussian,double>,DistributionStructArray<Gaussian,double>>(this.IndexedWeights_B, this.featureIndexes, this.Weights_uses_B[1]);
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			// Message to 'Weights_uses' from Replicate factor
			this.Weights_uses_B_toDef = ReplicateOp_Divide.ToDef<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B, this.Weights_uses_B_toDef);
			// Message to 'Weights_marginal' from Variable factor
			this.Weights_marginal_F = VariableOp.MarginalAverageConditional<DistributionStructArray<Gaussian,double>>(this.Weights_uses_B_toDef, this.weightPriors, this.Weights_marginal_F);
			this.Changed_numberOfIterationsDecreased_WeightPriors_FeatureIndexes_InstanceCount_InstanceFeatureCounts_7_iterationsDone = numberOfIterations;
		}

		/// <summary>
		/// Returns the marginal distribution for 'Weights' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Gaussian,double> WeightsMarginal()
		{
			return this.Weights_marginal_F;
		}

		/// <summary>
		/// Returns the output message (the posterior divided by the prior) for 'Weights' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The output message (the posterior divided by the prior)</returns>
		public DistributionStructArray<Gaussian,double> WeightsMarginalDividedByPrior()
		{
			return this.Weights_uses_B_toDef;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
