// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using MicrosoftResearch.Infer;
using MicrosoftResearch.Infer.Distributions;
using MicrosoftResearch.Infer.Factors;
using MicrosoftResearch.Infer.Collections;

namespace MicrosoftResearch.Infer.Models.User
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 2.6.41114.1 at 11:57 PM on Friday, November 14, 2014.
	/// </remarks>
	public partial class GaussianDenseMulticlassBpmTraining_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Field backing the InstanceCount property</summary>
		private int instanceCount;
		/// <summary>Field backing the FeatureCount property</summary>
		private int featureCount;
		/// <summary>Field backing the ClassCount property</summary>
		private int classCount;
		/// <summary>Field backing the FeatureValues property</summary>
		private double[][] featureValues;
		/// <summary>Field backing the WeightPriors property</summary>
		private DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> weightPriors;
		/// <summary>Field backing the WeightConstraints property</summary>
		private DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> weightConstraints;
		/// <summary>Field backing the Labels property</summary>
		private int[] labels;
		/// <summary>The number of iterations last computed by Constant. Set this to zero to force re-execution of Constant</summary>
		public int Constant_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_ClassCount. Set this to zero to force re-execution of Changed_ClassCount</summary>
		public int Changed_ClassCount_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_ClassCount_FeatureCount. Set this to zero to force re-execution of Changed_ClassCount_FeatureCount</summary>
		public int Changed_ClassCount_FeatureCount_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3. Set this to zero to force re-execution of Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3</summary>
		public int Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_iterationsDone;
		/// <summary>True if Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3 has performed initialisation. Set this to false to force re-execution of Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3</summary>
		public bool Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised;
		/// <summary>The number of iterations last computed by Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4. Set this to zero to force re-execution of Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4</summary>
		public int Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_iterationsDone;
		/// <summary>True if Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4 has performed initialisation. Set this to false to force re-execution of Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4</summary>
		public bool Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_isInitialised;
		/// <summary>The number of iterations last computed by Changed_ClassCount_FeatureCount_InstanceCount. Set this to zero to force re-execution of Changed_ClassCount_FeatureCount_InstanceCount</summary>
		public int Changed_ClassCount_FeatureCount_InstanceCount_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_InstanceCount. Set this to zero to force re-execution of Changed_InstanceCount</summary>
		public int Changed_InstanceCount_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_InstanceCount_ClassCount. Set this to zero to force re-execution of Changed_InstanceCount_ClassCount</summary>
		public int Changed_InstanceCount_ClassCount_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_InstanceCount_ClassCount_Labels. Set this to zero to force re-execution of Changed_InstanceCount_ClassCount_Labels</summary>
		public int Changed_InstanceCount_ClassCount_Labels_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9. Set this to zero to force re-execution of Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9</summary>
		public int Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_iterationsDone;
		/// <summary>True if Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9 has performed initialisation. Set this to false to force re-execution of Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9</summary>
		public bool Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_isInitialised;
		/// <summary>The number of iterations last computed by Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10. Set this to zero to force re-execution of Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10</summary>
		public int Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_iterationsDone;
		/// <summary>True if Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10 has performed initialisation. Set this to false to force re-execution of Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10</summary>
		public bool Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_isInitialised;
		/// <summary>The number of iterations last computed by Changed_FeatureCount. Set this to zero to force re-execution of Changed_FeatureCount</summary>
		public int Changed_FeatureCount_iterationsDone;
		/// <summary>The number of iterations last computed by Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12. Set this to zero to force re-execution of Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12</summary>
		public int Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone;
		/// <summary>True if Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12 has performed initialisation. Set this to false to force re-execution of Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12</summary>
		public bool Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_isInitialised;
		/// <summary>The number of iterations last computed by Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13. Set this to zero to force re-execution of Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13</summary>
		public int Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> FeatureScores_F;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Scores_F;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> NoisyScores_F;
		/// <summary>Buffer for ReplicateOp_Divide.UsesAverageConditional<Gaussian></summary>
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal<Gaussian></summary>
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef;
		public DistributionStructArray<Gaussian,double>[][][] NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F;
		/// <summary>Buffer for ReplicateOp_Divide.UsesAverageConditional<Gaussian></summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> MaxNoisyScore_rep_F_marginal;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal<Gaussian></summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> MaxNoisyScore_rep_B_toDef;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> MaxNoisyScore_rep_F;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> NoisyScoreDeltas_F;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> NoisyScoreDeltas_B;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B;
		public DistributionStructArray<Gaussian,double>[][][] NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> MaxNoisyScore_0__B;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> MaxNoisyScore_rep_B;
		/// <summary>Message from use of 'NoisyScores'</summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> NoisyScores_use_B;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Scores_B;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> FeatureScores_B;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[] SharedWeights_depth2_uses_F;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[] SharedWeights_depth2_uses_B;
		/// <summary>Messages from use of 'Weights'</summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[] Weights_uses_B;
		/// <summary>Messages to use of 'Weights'</summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[] Weights_uses_F;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> TransposedWeights_F;
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> TransposedWeights_B;
		/// <summary>Message to marginal of 'Weights'</summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Weights_marginal_F;
		/// <summary>Buffer for ReplicateOp_Divide.UsesAverageConditional<Gaussian></summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Weights_uses_F_ClassRange__FeatureRange__marginal;
		/// <summary>Buffer for ReplicateOp_Divide.UsesAverageConditional<Gaussian></summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Weights_rep_F_marginal;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal<Gaussian></summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Weights_rep_B_toDef;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> Weights_rep_F;
		public DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]> Weights_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal<Gaussian></summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> Weights_uses_B_ClassRange__FeatureRange__toDef;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'InstanceCount'</summary>
		public int InstanceCount
		{
			get {
				return this.instanceCount;
			}
			set {
				if (this.instanceCount!=value) {
					this.instanceCount = value;
					this.numberOfIterationsDone = 0;
					this.Changed_InstanceCount_iterationsDone = 0;
					this.Changed_InstanceCount_ClassCount_iterationsDone = 0;
					this.Changed_InstanceCount_ClassCount_Labels_iterationsDone = 0;
					this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_InstanceCount_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised = false;
					this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_isInitialised = false;
					this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_isInitialised = false;
					this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
				}
			}
		}

		/// <summary>The externally-specified value of 'FeatureCount'</summary>
		public int FeatureCount
		{
			get {
				return this.featureCount;
			}
			set {
				if (this.featureCount!=value) {
					this.featureCount = value;
					this.numberOfIterationsDone = 0;
					this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_isInitialised = false;
					this.Changed_FeatureCount_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_InstanceCount_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
				}
			}
		}

		/// <summary>The externally-specified value of 'ClassCount'</summary>
		public int ClassCount
		{
			get {
				return this.classCount;
			}
			set {
				if (this.classCount!=value) {
					this.classCount = value;
					this.numberOfIterationsDone = 0;
					this.Changed_InstanceCount_ClassCount_iterationsDone = 0;
					this.Changed_InstanceCount_ClassCount_Labels_iterationsDone = 0;
					this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_iterationsDone = 0;
					this.Changed_ClassCount_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_InstanceCount_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_iterationsDone = 0;
					this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
				}
			}
		}

		/// <summary>The externally-specified value of 'FeatureValues'</summary>
		public double[][] FeatureValues
		{
			get {
				return this.featureValues;
			}
			set {
				if ((value!=null)&&(value.Length!=this.instanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.instanceCount)+" was expected for variable \'FeatureValues\'");
				}
				this.featureValues = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'WeightPriors'</summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> WeightPriors
		{
			get {
				return this.weightPriors;
			}
			set {
				this.weightPriors = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'WeightConstraints'</summary>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> WeightConstraints
		{
			get {
				return this.weightConstraints;
			}
			set {
				this.weightConstraints = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_iterationsDone = 0;
				this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'Labels'</summary>
		public int[] Labels
		{
			get {
				return this.labels;
			}
			set {
				if ((value!=null)&&(value.Length!=this.instanceCount)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.instanceCount)+" was expected for variable \'Labels\'");
				}
				this.labels = value;
				this.numberOfIterationsDone = 0;
				this.Changed_InstanceCount_ClassCount_Labels_iterationsDone = 0;
				this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_iterationsDone = 0;
				this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
			}
		}

		#endregion

		#region Methods
		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="InstanceCount") {
				return this.InstanceCount;
			}
			if (variableName=="FeatureCount") {
				return this.FeatureCount;
			}
			if (variableName=="ClassCount") {
				return this.ClassCount;
			}
			if (variableName=="FeatureValues") {
				return this.FeatureValues;
			}
			if (variableName=="WeightPriors") {
				return this.WeightPriors;
			}
			if (variableName=="WeightConstraints") {
				return this.WeightConstraints;
			}
			if (variableName=="Labels") {
				return this.Labels;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="InstanceCount") {
				this.InstanceCount = (int)value;
				return ;
			}
			if (variableName=="FeatureCount") {
				this.FeatureCount = (int)value;
				return ;
			}
			if (variableName=="ClassCount") {
				this.ClassCount = (int)value;
				return ;
			}
			if (variableName=="FeatureValues") {
				this.FeatureValues = (double[][])value;
				return ;
			}
			if (variableName=="WeightPriors") {
				this.WeightPriors = (DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>)value;
				return ;
			}
			if (variableName=="WeightConstraints") {
				this.WeightConstraints = (DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>)value;
				return ;
			}
			if (variableName=="Labels") {
				this.Labels = (int[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="Weights") {
				return this.WeightsMarginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			if ((variableName=="Weights")&&(query=="MarginalDividedByPrior")) {
				return this.WeightsMarginalDividedByPrior();
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations<this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone) {
				this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_isInitialised = false;
				this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
			}
			this.Changed_InstanceCount();
			this.Changed_InstanceCount_ClassCount();
			this.Changed_InstanceCount_ClassCount_Labels();
			this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9(initialise);
			this.Constant();
			this.Changed_FeatureCount();
			this.Changed_ClassCount();
			this.Changed_ClassCount_FeatureCount();
			this.Changed_ClassCount_FeatureCount_InstanceCount();
			this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10(initialise);
			this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3(initialise);
			this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4(initialise);
			this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12(initialise);
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(this.numberOfIterationsDone+additionalIterations, false);
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Computations that depend on the observed value of InstanceCount</summary>
		private void Changed_InstanceCount()
		{
			if (this.Changed_InstanceCount_iterationsDone==1) {
				return ;
			}
			// Create array for replicates of 'FeatureScores_F'
			this.FeatureScores_F = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'Scores_F'
			this.Scores_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'NoisyScores_F'
			this.NoisyScores_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal'
			this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef'
			this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F'
			this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F = new DistributionStructArray<Gaussian,double>[this.instanceCount][][];
			// Create array for replicates of 'MaxNoisyScore_rep_F_marginal'
			this.MaxNoisyScore_rep_F_marginal = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'MaxNoisyScore_rep_B_toDef'
			this.MaxNoisyScore_rep_B_toDef = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'MaxNoisyScore_rep_F'
			this.MaxNoisyScore_rep_F = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'NoisyScoreDeltas_F'
			this.NoisyScoreDeltas_F = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'NoisyScoreDeltas_B'
			this.NoisyScoreDeltas_B = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B'
			this.NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B'
			this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B = new DistributionStructArray<Gaussian,double>[this.instanceCount][][];
			// Create array for replicates of 'MaxNoisyScore_0__B'
			this.MaxNoisyScore_0__B = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'MaxNoisyScore_rep_B'
			this.MaxNoisyScore_rep_B = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			// Create array for replicates of 'NoisyScores_use_B'
			this.NoisyScores_use_B = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'Scores_B'
			this.Scores_B = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.instanceCount);
			// Create array for replicates of 'FeatureScores_B'
			this.FeatureScores_B = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.instanceCount);
			this.Changed_InstanceCount_iterationsDone = 1;
			this.Changed_InstanceCount_ClassCount_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount and ClassCount</summary>
		private void Changed_InstanceCount_ClassCount()
		{
			if (this.Changed_InstanceCount_ClassCount_iterationsDone==1) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				// Create array for 'FeatureScores' Forwards messages.
				this.FeatureScores_F[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for 'Scores' Forwards messages.
				this.Scores_F[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.classCount);
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					this.Scores_F[InstanceRange][ClassRange] = Gaussian.Uniform();
				}
				// Create array for 'NoisyScores' Forwards messages.
				this.NoisyScores_F[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.classCount);
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					this.NoisyScores_F[InstanceRange][ClassRange] = Gaussian.Uniform();
				}
				// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal'
				this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef'
				this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F'
				this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange] = new DistributionStructArray<Gaussian,double>[this.classCount][];
				// Create array for replicates of 'MaxNoisyScore_rep_F_marginal'
				this.MaxNoisyScore_rep_F_marginal[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.classCount);
				// Create array for replicates of 'MaxNoisyScore_rep_B_toDef'
				this.MaxNoisyScore_rep_B_toDef[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.classCount);
				// Create array for replicates of 'MaxNoisyScore_rep_F'
				this.MaxNoisyScore_rep_F[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for replicates of 'NoisyScoreDeltas_F'
				this.NoisyScoreDeltas_F[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for replicates of 'NoisyScoreDeltas_B'
				this.NoisyScoreDeltas_B[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B'
				this.NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B'
				this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange] = new DistributionStructArray<Gaussian,double>[this.classCount][];
				// Create array for replicates of 'MaxNoisyScore_0__B'
				this.MaxNoisyScore_0__B[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for replicates of 'MaxNoisyScore_rep_B'
				this.MaxNoisyScore_rep_B[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
				// Create array for 'NoisyScores_use' Backwards messages.
				this.NoisyScores_use_B[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.classCount);
				// Create array for 'Scores' Backwards messages.
				this.Scores_B[InstanceRange] = new DistributionStructArray<Gaussian,double>(this.classCount);
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					this.Scores_B[InstanceRange][ClassRange] = Gaussian.Uniform();
				}
				// Create array for 'FeatureScores' Backwards messages.
				this.FeatureScores_B[InstanceRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
			}
			this.Changed_InstanceCount_ClassCount_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_InstanceCount_iterationsDone = 0;
			this.Changed_InstanceCount_ClassCount_Labels_iterationsDone = 0;
			this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount and ClassCount and Labels</summary>
		private void Changed_InstanceCount_ClassCount_Labels()
		{
			if (this.Changed_InstanceCount_ClassCount_Labels_iterationsDone==1) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				for(int ClassMaxNoisyScore = 0; ClassMaxNoisyScore<this.classCount; ClassMaxNoisyScore++) {
					if (this.labels[InstanceRange]==ClassMaxNoisyScore) {
						// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal'
						this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>(this.classCount);
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' from Replicate factor
							this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal[InstanceRange][ClassMaxNoisyScore][ClassRange] = ReplicateOp_Divide.MarginalInit<Gaussian>(this.NoisyScores_F[InstanceRange][ClassRange]);
						}
						// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef'
						this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>(this.classCount);
						// Create array for 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' Forwards messages.
						this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>[this.classCount];
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							// Create array for 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' Forwards messages.
							this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassRange] = new DistributionStructArray<Gaussian,double>(2);
							for(int _ind = 0; _ind<2; _ind++) {
								this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassRange][_ind] = Gaussian.Uniform();
							}
						}
						// Message to 'MaxNoisyScore_rep' from Replicate factor
						this.MaxNoisyScore_rep_F_marginal[InstanceRange][ClassMaxNoisyScore] = ReplicateOp_Divide.MarginalInit<Gaussian>(this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassMaxNoisyScore][0]);
						// Create array for 'MaxNoisyScore_rep' Forwards messages.
						this.MaxNoisyScore_rep_F[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>(this.classCount);
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							this.MaxNoisyScore_rep_F[InstanceRange][ClassMaxNoisyScore][ClassRange] = Gaussian.Uniform();
						}
						// Create array for replicates of 'NoisyScoreDeltas_F'
						this.NoisyScoreDeltas_F[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>(this.classCount);
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							if (ClassMaxNoisyScore!=ClassRange) {
								this.NoisyScoreDeltas_F[InstanceRange][ClassMaxNoisyScore][ClassRange] = Gaussian.Uniform();
							}
						}
						// Create array for replicates of 'NoisyScoreDeltas_B'
						this.NoisyScoreDeltas_B[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>(this.classCount);
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							if (ClassMaxNoisyScore!=ClassRange) {
								this.NoisyScoreDeltas_B[InstanceRange][ClassMaxNoisyScore][ClassRange] = Gaussian.Uniform();
							}
						}
						// Create array for replicates of 'NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B'
						this.NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>(this.classCount);
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							if (ClassMaxNoisyScore!=ClassRange) {
								this.NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B[InstanceRange][ClassMaxNoisyScore][ClassRange] = Gaussian.Uniform();
							}
						}
						// Create array for 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' Backwards messages.
						this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>[this.classCount];
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							// Create array for 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' Backwards messages.
							this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassRange] = new DistributionStructArray<Gaussian,double>(2);
						}
						// Create array for replicates of 'MaxNoisyScore_0__B'
						this.MaxNoisyScore_0__B[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>(this.classCount);
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							if (ClassMaxNoisyScore!=ClassRange) {
								this.MaxNoisyScore_0__B[InstanceRange][ClassMaxNoisyScore][ClassRange] = Gaussian.Uniform();
							}
						}
						// Create array for 'MaxNoisyScore_rep' Backwards messages.
						this.MaxNoisyScore_rep_B[InstanceRange][ClassMaxNoisyScore] = new DistributionStructArray<Gaussian,double>(this.classCount);
					}
				}
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					this.NoisyScores_use_B[InstanceRange][ClassRange] = Gaussian.Uniform();
				}
			}
			this.Changed_InstanceCount_ClassCount_Labels_iterationsDone = 1;
			this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of InstanceCount and ClassCount and Labels and must reset on changes to numberOfIterationsDecreased and FeatureCount and FeatureValues and WeightPriors and WeightConstraints</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9(bool initialise)
		{
			if ((this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_iterationsDone==1)&&((!initialise)||this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_isInitialised)) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				for(int ClassMaxNoisyScore = 0; ClassMaxNoisyScore<this.classCount; ClassMaxNoisyScore++) {
					if (this.labels[InstanceRange]==ClassMaxNoisyScore) {
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' from Replicate factor
							this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef[InstanceRange][ClassMaxNoisyScore][ClassRange] = ReplicateOp_Divide.ToDefInit<Gaussian>(this.NoisyScores_F[InstanceRange][ClassRange]);
						}
						// Message to 'MaxNoisyScore_rep' from Replicate factor
						this.MaxNoisyScore_rep_B_toDef[InstanceRange][ClassMaxNoisyScore] = ReplicateOp_Divide.ToDefInit<Gaussian>(this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassMaxNoisyScore][0]);
						for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
							for(int _ind = 0; _ind<2; _ind++) {
								this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassRange][_ind] = Gaussian.Uniform();
							}
							this.MaxNoisyScore_rep_B[InstanceRange][ClassMaxNoisyScore][ClassRange] = Gaussian.Uniform();
						}
					}
				}
			}
			this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_iterationsDone = 1;
			this.Changed_InstanceCount_ClassCount_Labels_Init_numberOfIterationsDecreased_FeatureCount_FeatureValues_9_isInitialised = true;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_iterationsDone==1) {
				return ;
			}
			this.Constant_iterationsDone = 1;
			this.Changed_ClassCount_iterationsDone = 0;
			this.Changed_FeatureCount_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of FeatureCount</summary>
		private void Changed_FeatureCount()
		{
			if (this.Changed_FeatureCount_iterationsDone==1) {
				return ;
			}
			// Create array for 'TransposedWeights' Forwards messages.
			this.TransposedWeights_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.featureCount);
			// Create array for 'TransposedWeights' Backwards messages.
			this.TransposedWeights_B = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.featureCount);
			this.Changed_FeatureCount_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of ClassCount</summary>
		private void Changed_ClassCount()
		{
			if (this.Changed_ClassCount_iterationsDone==1) {
				return ;
			}
			// Create array for 'SharedWeights_depth2_uses' Forwards messages.
			this.SharedWeights_depth2_uses_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[this.classCount];
			// Create array for 'SharedWeights_depth2_uses' Backwards messages.
			this.SharedWeights_depth2_uses_B = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[this.classCount];
			// Create array for 'Weights_uses' Backwards messages.
			this.Weights_uses_B = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[this.classCount];
			// Create array for replicates of 'Weights_uses_F_ClassRange__FeatureRange__marginal'
			this.Weights_uses_F_ClassRange__FeatureRange__marginal = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
			// Create array for 'Weights_uses' Forwards messages.
			this.Weights_uses_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>[this.classCount];
			// Create array for replicates of 'Weights_rep_F_marginal'
			this.Weights_rep_F_marginal = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
			// Create array for replicates of 'Weights_rep_B_toDef'
			this.Weights_rep_B_toDef = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
			// Create array for replicates of 'Weights_rep_F'
			this.Weights_rep_F = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.classCount);
			// Create array for replicates of 'Weights_rep_B'
			this.Weights_rep_B = new DistributionRefArray<DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>,double[][]>(this.classCount);
			// Create array for replicates of 'Weights_uses_B_ClassRange__FeatureRange__toDef'
			this.Weights_uses_B_ClassRange__FeatureRange__toDef = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
			// Create array for 'Weights_marginal' Forwards messages.
			this.Weights_marginal_F = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.classCount);
			this.Changed_ClassCount_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of ClassCount and FeatureCount</summary>
		private void Changed_ClassCount_FeatureCount()
		{
			if (this.Changed_ClassCount_FeatureCount_iterationsDone==1) {
				return ;
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				// Create array for 'SharedWeights_depth2_uses' Forwards messages.
				this.SharedWeights_depth2_uses_F[ClassRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.featureCount);
				// Create array for 'SharedWeights_depth2_uses' Backwards messages.
				this.SharedWeights_depth2_uses_B[ClassRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.featureCount);
				for(int _iv = 0; _iv<this.featureCount; _iv++) {
					// Create array for 'SharedWeights_depth2_uses' Forwards messages.
					this.SharedWeights_depth2_uses_F[ClassRange][_iv] = new DistributionStructArray<Gaussian,double>(2);
					// Create array for 'SharedWeights_depth2_uses' Backwards messages.
					this.SharedWeights_depth2_uses_B[ClassRange][_iv] = new DistributionStructArray<Gaussian,double>(2);
					for(int _ind = 0; _ind<2; _ind++) {
						this.SharedWeights_depth2_uses_B[ClassRange][_iv][_ind] = Gaussian.Uniform();
						this.SharedWeights_depth2_uses_F[ClassRange][_iv][_ind] = Gaussian.Uniform();
					}
				}
				// Create array for 'Weights_uses' Backwards messages.
				this.Weights_uses_B[ClassRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.featureCount);
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Create array for 'Weights_uses' Backwards messages.
					this.Weights_uses_B[ClassRange][FeatureRange] = new DistributionStructArray<Gaussian,double>(2);
				}
				// Create array for replicates of 'Weights_uses_F_ClassRange__FeatureRange__marginal'
				this.Weights_uses_F_ClassRange__FeatureRange__marginal[ClassRange] = new DistributionStructArray<Gaussian,double>(this.featureCount);
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Message to 'Weights_uses' from Replicate factor
					this.Weights_uses_F_ClassRange__FeatureRange__marginal[ClassRange][FeatureRange] = ReplicateOp_Divide.MarginalInit<Gaussian>(this.SharedWeights_depth2_uses_F[ClassRange][FeatureRange][0]);
				}
				// Create array for 'Weights_uses' Forwards messages.
				this.Weights_uses_F[ClassRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.featureCount);
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Create array for 'Weights_uses' Forwards messages.
					this.Weights_uses_F[ClassRange][FeatureRange] = new DistributionStructArray<Gaussian,double>(2);
					for(int _ind = 0; _ind<2; _ind++) {
						this.Weights_uses_F[ClassRange][FeatureRange][_ind] = Gaussian.Uniform();
					}
				}
				// Create array for replicates of 'Weights_rep_F_marginal'
				this.Weights_rep_F_marginal[ClassRange] = new DistributionStructArray<Gaussian,double>(this.featureCount);
				// Create array for replicates of 'Weights_rep_B_toDef'
				this.Weights_rep_B_toDef[ClassRange] = new DistributionStructArray<Gaussian,double>(this.featureCount);
				// Create array for replicates of 'Weights_rep_F'
				this.Weights_rep_F[ClassRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.featureCount);
				// Create array for replicates of 'Weights_rep_B'
				this.Weights_rep_B[ClassRange] = new DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]>(this.featureCount);
				// Create array for replicates of 'Weights_uses_B_ClassRange__FeatureRange__toDef'
				this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange] = new DistributionStructArray<Gaussian,double>(this.featureCount);
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Message to 'Weights_uses' from Replicate factor
					this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange] = ReplicateOp_Divide.ToDefInit<Gaussian>(this.SharedWeights_depth2_uses_F[ClassRange][FeatureRange][0]);
				}
			}
			for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
				// Create array for 'TransposedWeights' Forwards messages.
				this.TransposedWeights_F[FeatureRange] = new DistributionStructArray<Gaussian,double>(this.classCount);
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					this.TransposedWeights_F[FeatureRange][ClassRange] = Gaussian.Uniform();
				}
				// Create array for 'TransposedWeights' Backwards messages.
				this.TransposedWeights_B[FeatureRange] = new DistributionStructArray<Gaussian,double>(this.classCount);
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					this.TransposedWeights_B[FeatureRange][ClassRange] = Gaussian.Uniform();
				}
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				// Create array for 'Weights_marginal' Forwards messages.
				this.Weights_marginal_F[ClassRange] = new DistributionStructArray<Gaussian,double>(this.featureCount);
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					this.Weights_marginal_F[ClassRange][FeatureRange] = Gaussian.Uniform();
				}
			}
			this.Changed_ClassCount_FeatureCount_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_iterationsDone = 0;
			this.Changed_ClassCount_FeatureCount_InstanceCount_iterationsDone = 0;
			this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_iterationsDone = 0;
			this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of ClassCount and FeatureCount and InstanceCount</summary>
		private void Changed_ClassCount_FeatureCount_InstanceCount()
		{
			if (this.Changed_ClassCount_FeatureCount_InstanceCount_iterationsDone==1) {
				return ;
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Create array for 'Weights_rep' Forwards messages.
					this.Weights_rep_F[ClassRange][FeatureRange] = new DistributionStructArray<Gaussian,double>(this.instanceCount);
				}
			}
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
						this.Weights_rep_F[ClassRange][FeatureRange][InstanceRange] = Gaussian.Uniform();
					}
					// Create array for 'FeatureScores' Forwards messages.
					this.FeatureScores_F[InstanceRange][ClassRange] = new DistributionStructArray<Gaussian,double>(this.featureCount);
					for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
						this.FeatureScores_F[InstanceRange][ClassRange][FeatureRange] = Gaussian.Uniform();
					}
					// Create array for 'FeatureScores' Backwards messages.
					this.FeatureScores_B[InstanceRange][ClassRange] = new DistributionStructArray<Gaussian,double>(this.featureCount);
					for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
						this.FeatureScores_B[InstanceRange][ClassRange][FeatureRange] = Gaussian.Uniform();
					}
				}
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Create array for 'Weights_rep' Backwards messages.
					this.Weights_rep_B[ClassRange][FeatureRange] = new DistributionStructArray<Gaussian,double>(this.instanceCount);
				}
			}
			this.Changed_ClassCount_FeatureCount_InstanceCount_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of ClassCount and FeatureCount and InstanceCount and must reset on changes to numberOfIterationsDecreased and FeatureValues and Labels and WeightPriors and WeightConstraints</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10(bool initialise)
		{
			if ((this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_iterationsDone==1)&&((!initialise)||this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_isInitialised)) {
				return ;
			}
			for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
						this.Weights_rep_B[ClassRange][FeatureRange][InstanceRange] = Gaussian.Uniform();
					}
				}
			}
			this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_InstanceCount_Init_numberOfIterationsDecreased_FeatureValues_Labels_10_isInitialised = true;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of ClassCount and FeatureCount and must reset on changes to numberOfIterationsDecreased and InstanceCount and FeatureValues and Labels and WeightPriors and WeightConstraints</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3(bool initialise)
		{
			if ((this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_iterationsDone==1)&&((!initialise)||this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised)) {
				return ;
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					for(int _ind = 0; _ind<2; _ind++) {
						this.Weights_uses_B[ClassRange][FeatureRange][_ind] = Gaussian.Uniform();
					}
					// Message to 'Weights_rep' from Replicate factor
					this.Weights_rep_F_marginal[ClassRange][FeatureRange] = ReplicateOp_Divide.MarginalInit<Gaussian>(this.Weights_uses_F[ClassRange][FeatureRange][1]);
					// Message to 'Weights_rep' from Replicate factor
					this.Weights_rep_B_toDef[ClassRange][FeatureRange] = ReplicateOp_Divide.ToDefInit<Gaussian>(this.Weights_uses_F[ClassRange][FeatureRange][1]);
				}
			}
			this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_Init_numberOfIterationsDecreased_InstanceCount_FeatureValues_Labels_3_isInitialised = true;
			this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_iterationsDone = 0;
			this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of ClassCount and FeatureCount and WeightConstraints and must reset on changes to numberOfIterationsDecreased and InstanceCount and FeatureValues and Labels and WeightPriors</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4(bool initialise)
		{
			if ((this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_iterationsDone==1)&&((!initialise)||this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_isInitialised)) {
				return ;
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Message to 'Weights_uses' from Copy factor
					this.Weights_uses_B[ClassRange][FeatureRange][0] = ArrayHelper.SetTo<Gaussian>(this.Weights_uses_B[ClassRange][FeatureRange][0], this.weightConstraints[ClassRange][FeatureRange]);
					// Message to 'Weights_uses' from Replicate factor
					this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange] = ReplicateOp_Divide.ToDef<Gaussian>(this.Weights_uses_B[ClassRange][FeatureRange], this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange]);
					// Message to 'SharedWeights_depth2_uses' from Copy factor
					this.SharedWeights_depth2_uses_B[ClassRange][FeatureRange][0] = ArrayHelper.SetTo<Gaussian>(this.SharedWeights_depth2_uses_B[ClassRange][FeatureRange][0], this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange]);
				}
			}
			this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_WeightConstraints_Init_numberOfIterationsDecreased_InstanceCount_Fea4_isInitialised = true;
			this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone = 0;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of ClassCount and FeatureCount and WeightPriors and WeightConstraints and must reset on changes to numberOfIterationsDecreased and InstanceCount and FeatureValues and Labels</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12(bool initialise)
		{
			if ((this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone==1)&&((!initialise)||this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_isInitialised)) {
				return ;
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				for(int _iv = 0; _iv<this.featureCount; _iv++) {
					// Message to 'SharedWeights_depth2_uses' from Replicate factor
					this.SharedWeights_depth2_uses_F[ClassRange][_iv][1] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(this.SharedWeights_depth2_uses_B[ClassRange][_iv], this.weightPriors[ClassRange][_iv], 1, this.SharedWeights_depth2_uses_F[ClassRange][_iv][1]);
				}
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Message to 'TransposedWeights' from Copy factor
					this.TransposedWeights_F[FeatureRange][ClassRange] = ArrayHelper.SetTo<Gaussian>(this.TransposedWeights_F[FeatureRange][ClassRange], this.SharedWeights_depth2_uses_F[ClassRange][FeatureRange][1]);
				}
			}
			for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
				// Message to 'TransposedWeights' from Sum factor
				this.TransposedWeights_B[FeatureRange] = FastSumOp.ArrayAverageConditional<DistributionStructArray<Gaussian,double>>(0.0, this.TransposedWeights_F[FeatureRange], this.TransposedWeights_B[FeatureRange]);
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					// Message to 'SharedWeights_depth2_uses' from Copy factor
					this.SharedWeights_depth2_uses_B[ClassRange][FeatureRange][1] = ArrayHelper.SetTo<Gaussian>(this.SharedWeights_depth2_uses_B[ClassRange][FeatureRange][1], this.TransposedWeights_B[FeatureRange][ClassRange]);
				}
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				for(int _iv = 0; _iv<this.featureCount; _iv++) {
					// Message to 'SharedWeights_depth2_uses' from Replicate factor
					this.SharedWeights_depth2_uses_F[ClassRange][_iv][0] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(this.SharedWeights_depth2_uses_B[ClassRange][_iv], this.weightPriors[ClassRange][_iv], 0, this.SharedWeights_depth2_uses_F[ClassRange][_iv][0]);
				}
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Message to 'Weights_uses' from Replicate factor
					this.Weights_uses_F_ClassRange__FeatureRange__marginal[ClassRange][FeatureRange] = ReplicateOp_Divide.Marginal<Gaussian>(this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange], this.SharedWeights_depth2_uses_F[ClassRange][FeatureRange][0], this.Weights_uses_F_ClassRange__FeatureRange__marginal[ClassRange][FeatureRange]);
					// Message to 'Weights_uses' from Replicate factor
					this.Weights_uses_F[ClassRange][FeatureRange][1] = ReplicateOp_Divide.UsesAverageConditional<Gaussian>(this.Weights_rep_B_toDef[ClassRange][FeatureRange], this.Weights_uses_F_ClassRange__FeatureRange__marginal[ClassRange][FeatureRange], 1, this.Weights_uses_F[ClassRange][FeatureRange][1]);
					// Message to 'Weights_rep' from Replicate factor
					this.Weights_rep_F_marginal[ClassRange][FeatureRange] = ReplicateOp_Divide.Marginal<Gaussian>(this.Weights_rep_B_toDef[ClassRange][FeatureRange], this.Weights_uses_F[ClassRange][FeatureRange][1], this.Weights_rep_F_marginal[ClassRange][FeatureRange]);
				}
			}
			this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_iterationsDone = 1;
			this.Changed_ClassCount_FeatureCount_WeightPriors_WeightConstraints_Init_numberOfIterationsDecreased_Inst12_isInitialised = true;
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = 0;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and ClassCount and FeatureCount and InstanceCount and FeatureValues and Labels and WeightPriors and WeightConstraints</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13(int numberOfIterations)
		{
			if (this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone==numberOfIterations) {
				return ;
			}
			for(int iteration = this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone; iteration<numberOfIterations; iteration++) {
				for(int InstanceRange = 0; InstanceRange<this.instanceCount; InstanceRange++) {
					for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
						for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
							// Message to 'Weights_rep' from Replicate factor
							this.Weights_rep_F[ClassRange][FeatureRange][InstanceRange] = ReplicateOp_Divide.UsesAverageConditional<Gaussian>(this.Weights_rep_B[ClassRange][FeatureRange][InstanceRange], this.Weights_rep_F_marginal[ClassRange][FeatureRange], InstanceRange, this.Weights_rep_F[ClassRange][FeatureRange][InstanceRange]);
							// Message to 'FeatureScores' from Product factor
							this.FeatureScores_F[InstanceRange][ClassRange][FeatureRange] = GaussianProductOp.ProductAverageConditional(this.featureValues[InstanceRange][FeatureRange], this.Weights_rep_F[ClassRange][FeatureRange][InstanceRange]);
						}
						// Message to 'Scores' from Sum factor
						this.Scores_F[InstanceRange][ClassRange] = FastSumOp.SumAverageConditional(this.FeatureScores_F[InstanceRange][ClassRange]);
						// Message to 'NoisyScores' from GaussianFromMeanAndVariance factor
						this.NoisyScores_F[InstanceRange][ClassRange] = GaussianFromMeanAndVarianceOp.SampleAverageConditional(this.Scores_F[InstanceRange][ClassRange], 1.0);
						for(int ClassMaxNoisyScore = 0; ClassMaxNoisyScore<this.classCount; ClassMaxNoisyScore++) {
							if (this.labels[InstanceRange]==ClassMaxNoisyScore) {
								// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' from Replicate factor
								this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal[InstanceRange][ClassMaxNoisyScore][ClassRange] = ReplicateOp_Divide.Marginal<Gaussian>(this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef[InstanceRange][ClassMaxNoisyScore][ClassRange], this.NoisyScores_F[InstanceRange][ClassRange], this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal[InstanceRange][ClassMaxNoisyScore][ClassRange]);
								// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' from Replicate factor
								this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassRange][0] = ReplicateOp_Divide.UsesAverageConditional<Gaussian>(this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassRange][0], this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal[InstanceRange][ClassMaxNoisyScore][ClassRange], 0, this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassRange][0]);
							}
						}
					}
					for(int ClassMaxNoisyScore = 0; ClassMaxNoisyScore<this.classCount; ClassMaxNoisyScore++) {
						if (this.labels[InstanceRange]==ClassMaxNoisyScore) {
							// Message to 'MaxNoisyScore_rep' from Replicate factor
							this.MaxNoisyScore_rep_F_marginal[InstanceRange][ClassMaxNoisyScore] = ReplicateOp_Divide.Marginal<Gaussian>(this.MaxNoisyScore_rep_B_toDef[InstanceRange][ClassMaxNoisyScore], this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassMaxNoisyScore][0], this.MaxNoisyScore_rep_F_marginal[InstanceRange][ClassMaxNoisyScore]);
							for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
								// Message to 'MaxNoisyScore_rep' from Replicate factor
								this.MaxNoisyScore_rep_F[InstanceRange][ClassMaxNoisyScore][ClassRange] = ReplicateOp_Divide.UsesAverageConditional<Gaussian>(this.MaxNoisyScore_rep_B[InstanceRange][ClassMaxNoisyScore][ClassRange], this.MaxNoisyScore_rep_F_marginal[InstanceRange][ClassMaxNoisyScore], ClassRange, this.MaxNoisyScore_rep_F[InstanceRange][ClassMaxNoisyScore][ClassRange]);
								// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' from Replicate factor
								this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassRange][1] = ReplicateOp_Divide.UsesAverageConditional<Gaussian>(this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassRange][1], this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F_ClassRange__marginal[InstanceRange][ClassMaxNoisyScore][ClassRange], 1, this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassRange][1]);
								if (ClassMaxNoisyScore!=ClassRange) {
									// Message to 'NoisyScoreDeltas' from Difference factor
									this.NoisyScoreDeltas_F[InstanceRange][ClassMaxNoisyScore][ClassRange] = DoublePlusOp.AAverageConditional(this.MaxNoisyScore_rep_F[InstanceRange][ClassMaxNoisyScore][ClassRange], this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassRange][1]);
									// Message to 'NoisyScoreDeltas' from IsPositive factor
									this.NoisyScoreDeltas_B[InstanceRange][ClassMaxNoisyScore][ClassRange] = IsPositiveOp_Proper.XAverageConditional(Bernoulli.PointMass(true), this.NoisyScoreDeltas_F[InstanceRange][ClassMaxNoisyScore][ClassRange]);
									// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0_' from Difference factor
									this.NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B[InstanceRange][ClassMaxNoisyScore][ClassRange] = DoublePlusOp.BAverageConditional(this.MaxNoisyScore_rep_F[InstanceRange][ClassMaxNoisyScore][ClassRange], this.NoisyScoreDeltas_B[InstanceRange][ClassMaxNoisyScore][ClassRange]);
									// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' from Copy factor
									this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassRange][1] = ArrayHelper.SetTo<Gaussian>(this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassRange][1], this.NoisyScores_ClassRange_ClassMaxNoisyScore_ClassRange_0__B[InstanceRange][ClassMaxNoisyScore][ClassRange]);
									// Message to 'MaxNoisyScore_0_' from Difference factor
									this.MaxNoisyScore_0__B[InstanceRange][ClassMaxNoisyScore][ClassRange] = DoublePlusOp.SumAverageConditional(this.NoisyScoreDeltas_B[InstanceRange][ClassMaxNoisyScore][ClassRange], this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_F[InstanceRange][ClassMaxNoisyScore][ClassRange][1]);
									// Message to 'MaxNoisyScore_rep' from Copy factor
									this.MaxNoisyScore_rep_B[InstanceRange][ClassMaxNoisyScore][ClassRange] = ArrayHelper.SetTo<Gaussian>(this.MaxNoisyScore_rep_B[InstanceRange][ClassMaxNoisyScore][ClassRange], this.MaxNoisyScore_0__B[InstanceRange][ClassMaxNoisyScore][ClassRange]);
								}
							}
							// Message to 'MaxNoisyScore_rep' from Replicate factor
							this.MaxNoisyScore_rep_B_toDef[InstanceRange][ClassMaxNoisyScore] = ReplicateOp_Divide.ToDef<Gaussian>(this.MaxNoisyScore_rep_B[InstanceRange][ClassMaxNoisyScore], this.MaxNoisyScore_rep_B_toDef[InstanceRange][ClassMaxNoisyScore]);
							// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' from Copy factor
							this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassMaxNoisyScore][0] = ArrayHelper.SetTo<Gaussian>(this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassMaxNoisyScore][0], this.MaxNoisyScore_rep_B_toDef[InstanceRange][ClassMaxNoisyScore]);
						}
					}
					for(int ClassMaxNoisyScore = 0; ClassMaxNoisyScore<this.classCount; ClassMaxNoisyScore++) {
						if (this.labels[InstanceRange]==ClassMaxNoisyScore) {
							for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
								// Message to 'NoisyScores_ClassRange_ClassMaxNoisyScore_uses' from Replicate factor
								this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef[InstanceRange][ClassMaxNoisyScore][ClassRange] = ReplicateOp_Divide.ToDef<Gaussian>(this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B[InstanceRange][ClassMaxNoisyScore][ClassRange], this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef[InstanceRange][ClassMaxNoisyScore][ClassRange]);
								// Message to 'NoisyScores_use' from Copy factor
								this.NoisyScores_use_B[InstanceRange][ClassRange] = ArrayHelper.SetTo<Gaussian>(this.NoisyScores_use_B[InstanceRange][ClassRange], this.NoisyScores_ClassRange_ClassMaxNoisyScore_uses_B_ClassRange__toDef[InstanceRange][ClassMaxNoisyScore][ClassRange]);
							}
						}
					}
					for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
						// Message to 'Scores' from GaussianFromMeanAndVariance factor
						this.Scores_B[InstanceRange][ClassRange] = GaussianFromMeanAndVarianceOp.MeanAverageConditional(this.NoisyScores_use_B[InstanceRange][ClassRange], 1.0);
						// Message to 'FeatureScores' from Sum factor
						this.FeatureScores_B[InstanceRange][ClassRange] = FastSumOp.ArrayAverageConditional<DistributionStructArray<Gaussian,double>>(this.Scores_B[InstanceRange][ClassRange], this.Scores_F[InstanceRange][ClassRange], this.FeatureScores_F[InstanceRange][ClassRange], this.FeatureScores_B[InstanceRange][ClassRange]);
						for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
							// Message to 'Weights_rep' from Product factor
							this.Weights_rep_B[ClassRange][FeatureRange][InstanceRange] = GaussianProductOp.BAverageConditional(this.FeatureScores_B[InstanceRange][ClassRange][FeatureRange], this.featureValues[InstanceRange][FeatureRange]);
							this.Weights_rep_F_marginal[ClassRange][FeatureRange] = ReplicateOp_Divide.MarginalIncrement<Gaussian>(this.Weights_rep_F_marginal[ClassRange][FeatureRange], this.Weights_rep_F[ClassRange][FeatureRange][InstanceRange], this.Weights_rep_B[ClassRange][FeatureRange][InstanceRange]);
						}
					}
				}
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
						// Message to 'Weights_rep' from Replicate factor
						this.Weights_rep_B_toDef[ClassRange][FeatureRange] = ReplicateOp_Divide.ToDef<Gaussian>(this.Weights_rep_B[ClassRange][FeatureRange], this.Weights_rep_B_toDef[ClassRange][FeatureRange]);
						// Message to 'Weights_uses' from Replicate factor
						this.Weights_uses_B[ClassRange][FeatureRange][1] = ArrayHelper.SetTo<Gaussian>(this.Weights_uses_B[ClassRange][FeatureRange][1], this.Weights_rep_B_toDef[ClassRange][FeatureRange]);
						// Message to 'Weights_uses' from Replicate factor
						this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange] = ReplicateOp_Divide.ToDef<Gaussian>(this.Weights_uses_B[ClassRange][FeatureRange], this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange]);
						// Message to 'SharedWeights_depth2_uses' from Copy factor
						this.SharedWeights_depth2_uses_B[ClassRange][FeatureRange][0] = ArrayHelper.SetTo<Gaussian>(this.SharedWeights_depth2_uses_B[ClassRange][FeatureRange][0], this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange]);
					}
					for(int _iv = 0; _iv<this.featureCount; _iv++) {
						// Message to 'SharedWeights_depth2_uses' from Replicate factor
						this.SharedWeights_depth2_uses_F[ClassRange][_iv][1] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(this.SharedWeights_depth2_uses_B[ClassRange][_iv], this.weightPriors[ClassRange][_iv], 1, this.SharedWeights_depth2_uses_F[ClassRange][_iv][1]);
					}
					for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
						// Message to 'TransposedWeights' from Copy factor
						this.TransposedWeights_F[FeatureRange][ClassRange] = ArrayHelper.SetTo<Gaussian>(this.TransposedWeights_F[FeatureRange][ClassRange], this.SharedWeights_depth2_uses_F[ClassRange][FeatureRange][1]);
					}
				}
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Message to 'TransposedWeights' from Sum factor
					this.TransposedWeights_B[FeatureRange] = FastSumOp.ArrayAverageConditional<DistributionStructArray<Gaussian,double>>(0.0, this.TransposedWeights_F[FeatureRange], this.TransposedWeights_B[FeatureRange]);
					for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
						// Message to 'SharedWeights_depth2_uses' from Copy factor
						this.SharedWeights_depth2_uses_B[ClassRange][FeatureRange][1] = ArrayHelper.SetTo<Gaussian>(this.SharedWeights_depth2_uses_B[ClassRange][FeatureRange][1], this.TransposedWeights_B[FeatureRange][ClassRange]);
					}
				}
				for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
					for(int _iv = 0; _iv<this.featureCount; _iv++) {
						// Message to 'SharedWeights_depth2_uses' from Replicate factor
						this.SharedWeights_depth2_uses_F[ClassRange][_iv][0] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(this.SharedWeights_depth2_uses_B[ClassRange][_iv], this.weightPriors[ClassRange][_iv], 0, this.SharedWeights_depth2_uses_F[ClassRange][_iv][0]);
					}
					for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
						// Message to 'Weights_uses' from Replicate factor
						this.Weights_uses_F_ClassRange__FeatureRange__marginal[ClassRange][FeatureRange] = ReplicateOp_Divide.Marginal<Gaussian>(this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange], this.SharedWeights_depth2_uses_F[ClassRange][FeatureRange][0], this.Weights_uses_F_ClassRange__FeatureRange__marginal[ClassRange][FeatureRange]);
						// Message to 'Weights_uses' from Replicate factor
						this.Weights_uses_F[ClassRange][FeatureRange][1] = ReplicateOp_Divide.UsesAverageConditional<Gaussian>(this.Weights_rep_B_toDef[ClassRange][FeatureRange], this.Weights_uses_F_ClassRange__FeatureRange__marginal[ClassRange][FeatureRange], 1, this.Weights_uses_F[ClassRange][FeatureRange][1]);
						// Message to 'Weights_rep' from Replicate factor
						this.Weights_rep_F_marginal[ClassRange][FeatureRange] = ReplicateOp_Divide.Marginal<Gaussian>(this.Weights_rep_B_toDef[ClassRange][FeatureRange], this.Weights_uses_F[ClassRange][FeatureRange][1], this.Weights_rep_F_marginal[ClassRange][FeatureRange]);
					}
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int ClassRange = 0; ClassRange<this.classCount; ClassRange++) {
				for(int FeatureRange = 0; FeatureRange<this.featureCount; FeatureRange++) {
					// Message to 'Weights_marginal' from DerivedVariable factor
					this.Weights_marginal_F[ClassRange][FeatureRange] = DerivedVariableOp.MarginalAverageConditional<Gaussian>(this.Weights_uses_B_ClassRange__FeatureRange__toDef[ClassRange][FeatureRange], this.SharedWeights_depth2_uses_F[ClassRange][FeatureRange][0], this.Weights_marginal_F[ClassRange][FeatureRange]);
				}
			}
			this.Changed_numberOfIterationsDecreased_ClassCount_FeatureCount_InstanceCount_FeatureValues_Labels_Weigh13_iterationsDone = numberOfIterations;
		}

		/// <summary>
		/// Returns the marginal distribution for 'Weights' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> WeightsMarginal()
		{
			return this.Weights_marginal_F;
		}

		/// <summary>
		/// Returns the output message (the posterior divided by the prior) for 'Weights' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The output message (the posterior divided by the prior)</returns>
		public DistributionRefArray<DistributionStructArray<Gaussian,double>,double[]> WeightsMarginalDividedByPrior()
		{
			return this.Weights_uses_B_ClassRange__FeatureRange__toDef;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
